package de.xares.conference.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TimeslotAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTimeslotAllPropertiesEquals(Timeslot expected, Timeslot actual) {
        assertTimeslotAutoGeneratedPropertiesEquals(expected, actual);
        assertTimeslotAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTimeslotAllUpdatablePropertiesEquals(Timeslot expected, Timeslot actual) {
        assertTimeslotUpdatableFieldsEquals(expected, actual);
        assertTimeslotUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTimeslotAutoGeneratedPropertiesEquals(Timeslot expected, Timeslot actual) {
        assertThat(actual)
            .as("Verify Timeslot auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTimeslotUpdatableFieldsEquals(Timeslot expected, Timeslot actual) {
        assertThat(actual)
            .as("Verify Timeslot relevant properties")
            .satisfies(a -> assertThat(a.getStart()).as("check start").isEqualTo(expected.getStart()))
            .satisfies(a -> assertThat(a.getEnd()).as("check end").isEqualTo(expected.getEnd()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTimeslotUpdatableRelationshipsEquals(Timeslot expected, Timeslot actual) {
        // empty method
    }
}
